### ISSUE TITLE
Min, Max monoids for numbers

### ISSUE THREAD

**Issue by kubukoz** [ChristopherDavenport/monoids#10]

**Comment by kubukoz** [comment]
Actually, it'd only make sense for semigroups... probably worth considering anyways

**Comment by LukaJCB** [comment]
I feel like this can be closed, they can be found in `semigroups`: https://github.com/ChristopherDavenport/semigroups/blob/master/core/src/main/scala/io/chrisdavenport/semigroups/Max.scala

**Comment by kubukoz** [comment]
Agree, didn't realize this existed back then :)
